name: thebridge
main: plugily.projects.thebridge.Main
authors: [2Wild4You, Tigerpanzer, Plajer]
version: 0.0.1
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  thebridge:
    description: thebridge commands
    aliases: [ac, among]
  thebridgeAdmin:
    description: thebridge admin commands
    aliases: [aca, amongadmin]