name: AmongCraft
main: plugily.projects.amongcraft.Main
authors: [2Wild4You, Tigerpanzer, Plajer]
version: 0.0.1
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  AmongCraft:
    description: Among Craft commands
    aliases: [ac, among]
  AmongCraftAdmin:
    description: Among Craft admin commands
    aliases: [aca, amongadmin]