name: thebridge
main: plugily.projects.thebridge.Main
authors: [2Wild4You, Tigerpanzer, Plajer, montlikadani]
version: ${project.version}
api-version: 1.13
softdepend: [CorpseReborn, PlaceholderAPI, Parties, Spigot-Party-API-PAF, PartyAndFriends]

commands:
  thebridge:
    description: thebridge commands
    usage: "\u00A76Correct usage: /mm [stats/leave/join]"
    aliases: [mm, murder]
  thebridgeAdmin:
    description: thebridge admin commands
    usage: "\u00A76Correct usage: /mma [option]"
    aliases: [mma, murderadmin]

permissions:
  thebridge.admin.*:
    default: op
    children:
      thebridge.updatenotify: true
      thebridge.command.override: true
      thebridge.admin: true
      thebridge.admin.setup: true
      thebridge.admin.create: true
      thebridge.admin.delete: true
      thebridge.admin.list: true
      thebridge.admin.stopgame: true
      thebridge.admin.forcestart: true
      thebridge.admin.addsign: true
      thebridge.admin.sign.create: true
      thebridge.admin.sign.break: true